server:
  port: ${PAYMENT_SVC_DISCOVERY_PORT:8761}
spring:
  application:
    name: payment-service-discovery
  main:
    banner-mode: off
eureka:
  instance:
    hostname: ${PAYMENT_SVC_DISCOVERY_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    root: INFO