server:
  port: ${FUNDTRANSFER_SVC_PORT:8080}

spring:
  application:
    name: fundtransfer-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fundtransfers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: off

eureka:
  client:
    serviceUrl:
      defaultZone: ${PAYMENT_SVC_DISCOVERY_URL:http://localhost:8761/eureka}

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: '*'

cors:
  origin: ${CORS_ORIGIN:*}