server:
  port: 8080

spring:
  application:
    name: fundtransfer-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: off

logging:
  level:
    root: info

cors:
  origin: ${CORS_ORIGIN:*}