server:
  port: ${FUNDTRANSFER_SVC_PORT:8080}

spring:
  application:
    name: fundtransfer-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fundtransfers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: off

logging:
  level:
    root: info

cors:
  origin: ${CORS_ORIGIN:*}