name: fundtransfer-service
on:
  push:
    branches:
      - master

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: microsoft
      - run: | 
         cp -r fundtransfer-service/src ./src
         cp fundtransfer-service/pom.xml .
         mvn clean install -U    