name: payment-service-discovery
on:
  push:
    branches:
      - master

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven- 
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: microsoft
      - run: | 
         cp -r payment-service-discovery/src ./src
         cp payment-service-discovery/pom.xml .
         mvn clean install -U    